run:
  deadline: 5m
  tests: true

linters:
  enable:
    - gofmt
    - stylecheck
    - staticcheck
    - vet
    - misspell
    - ineffassign
    - deadcode
    - errcheck
    - structcheck
    - unused
    - varcheck
  enable-all: false
  fast: false

linters-settings:
  misspell:
    locale: US
